### ISSUE TITLE
Funcionário cadastra uma nova promoção

### ISSUE THREAD

**Issue by petragrunheidt** [TreinaDev/payment-antifraud#11]
Funcionário acessa pagina de cadastrar nova promoção e preenche os campos:

- Data de início (datetime)
- Data de fim (datetime)
- Nome (not null, String)
- Desconto (em %) - Integer 
- Produtos habilitados para a promoção - array de strings consumidos via API
- Valor máximo de desconto (em reais) - decimal
- Número máximo de utilizações (integer)
- Cupom: código de 8 dígitos gerado automaticamente

**Comment by ana-borowsky** [comment]
Falta gerar o código do cupom automaticamente.
